version: 0.2

phases:
  pre_build:
    commands:
      - echo copy the env file...
      - cp env/.env.$ENV .env
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building the docker image..."
      - docker build -t $REPOSITORY_URI_BSG_PORTAL_FRONTEND:latest .
      - docker tag $REPOSITORY_URI_BSG_PORTAL_FRONTEND:latest $REPOSITORY_URI_BSG_PORTAL_FRONTEND:$IMAGE_TAG
  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo Pushing the Docker images to ECR...
      - docker push $REPOSITORY_URI_BSG_PORTAL_FRONTEND:latest
      - docker push $REPOSITORY_URI_BSG_PORTAL_FRONTEND:$IMAGE_TAG